
spring:
  profiles:
    active: prod

---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/module?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Password!

  config:
    activate:
      on-profile: prod

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

    generate-ddl: true
    #show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect

  devtools:
    livereload:
      enabled: true


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

